title: excluded middle
author: leonardo lima
description: more noise than signal
url: https://excludedmiddle.github.io
baseurl: "/gistbook"

theme: no-style-please

theme_config:
  appearance: "dark"
  back_home_text: "home"
  date_format: "%Y-%m-%d"
  show_description: true

collections:
  tags:
    output: true
    permalink: /:collection/:name

feed:
  excerpt_only: true

exclude:
  - bootstrap.py
  - requirements.txt
  - LICENSE
  - README.md
  - templates
